version: "3.8"

services:
  spends-bot:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: spends-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - ./data:/data
    env_file:
      - .env
