version: "3.8"

services:
  spends-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spends-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - ./data:/data
    env_file:
      - .env
    depends_on:
      - flask-charts # ← Запускать после Flask
    networks:
      - spends-network

  # Flask микросервис
  flask-charts:
    build:
      context: ./pkg/FlaskApp
      dockerfile: Dockerfile
    container_name: flask-charts
    restart: unless-stopped
    ports:
      - "5005:5005"
    networks:
      - spends-network

networks:
  spends-network:
    driver: bridge
